/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:e63fd18c-57cd-4d9a-a93b-921560e27a98",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_oQRb18GyL",
    "aws_user_pools_web_client_id": "50aog49i83qu4csg33jb63cit",
    "oauth": {
        "domain": "cmpe281project227599aee-27599aee-sampledev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://app.showtimedrivein.com/",
        "redirectSignOut": "https://app.showtimedrivein.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://4tq5jvspene4lfdtiugm3hu4wq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://58822gs9r9.execute-api.us-east-1.amazonaws.com/sampledev",
            "region": "us-east-1"
        }
    ],
    "aws_user_files_s3_bucket": "cmpe281-project2-content-store163219-sampledev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_bots": "enable",
    "aws_bots_config": [
        {
            "name": "DoctorBot_sampledev",
            "alias": "$LATEST",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
